# Generated by Django 4.2.1 on 2023-06-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="truckprices",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
